### ISSUE TITLE
Add readme to each example explaining what scripts to run

### ISSUE THREAD

**Issue by nklayman** [tauri-apps/smoke-tests#5]
It would be nice if each example had a short readme explaining what scripts need to be run before `tauri dev/build`, or if a certain folder needs to be hosted on a certain port.

**Comment by Aidan-Chelig** [comment]
At the moment the examples aren't perfect by any means I intend on making the build/dev process roughly equivalent for each one.

**Comment by lukethacoder** [comment]
Anyone trying to get these examples running (while we are documentation-less).

- clone the main [repo](https://github.com/tauri-apps/tauri) `git clone https://github.com/tauri-apps/tauri`
- `cd ./tauri`
- `git clone https://github.com/tauri-apps/examples`
- edit the `.scripts` file (depending on your platform of choice) to point the examples PATH to the *examples* folder we cloned.

As a side note, I couldn't manage to get the Windows version working. But WSL + X Server seemed to do the trick. Also make sure your React App (or devserver of choice) is running before you run `yarn tauri:source:dev`

**Comment by lucasfernog** [comment]
The recommended way to run the smoke tests is through the tauri monorepo and `cargo mask`. I think we can close this since this isn't "examples" anymore.
